package bseprules;
global com.example.demo.bus.EventBus eventBus;
import com.example.demo.events.*;
import com.example.demo.logging.*;

rule "Detect alarm Stupid alarm rule 2_11"
when
	$s: String(this == "This should never happen.")
then
    System.out.println($s);
	System.out.println("Detected: Inaccessible alarm.");
	eventBus.onAlarm(new AlarmOccurred("Inaccessible alarm."));
end

rule "Detect alarm Stupid alarm rule 1_10"
when
	String(this == "This should never happen.")
then

	System.out.println("Detected: I told you this should never happen.");
	eventBus.onAlarm(new AlarmOccurred("I told you this should never happen."));
end

rule "Detect alarm Stupid alarm rule 2_9"
when
	$s: String(this == "This should never happen.")
then
    System.out.println($s);
	System.out.println("Detected: Inaccessible alarm.");
	eventBus.onAlarm(new AlarmOccurred("Inaccessible alarm."));
end

rule "Detect alarm Stupid alarm rule 1_8"
when
	String(this == "This should never happen.")
then

	System.out.println("Detected: I told you this should never happen.");
	eventBus.onAlarm(new AlarmOccurred("I told you this should never happen."));
end

rule "Detect alarm Stupid alarm rule 2_7"
when
	$s: String(this == "This should never happen.")
then
    System.out.println($s);
	System.out.println("Detected: Inaccessible alarm.");
	eventBus.onAlarm(new AlarmOccurred("Inaccessible alarm."));
end

rule "Detect alarm Stupid alarm rule 1_6"
when
	String(this == "This should never happen.")
then

	System.out.println("Detected: I told you this should never happen.");
	eventBus.onAlarm(new AlarmOccurred("I told you this should never happen."));
end

rule "Detect alarm Stupid alarm rule 2_5"
when
	$s: String(this == "This should never happen.")
then
    System.out.println($s);
	System.out.println("Detected: Inaccessible alarm.");
	eventBus.onAlarm(new AlarmOccurred("Inaccessible alarm."));
end

rule "Detect alarm Stupid alarm rule 1_4"
when
	String(this == "This should never happen.")
then

	System.out.println("Detected: I told you this should never happen.");
	eventBus.onAlarm(new AlarmOccurred("I told you this should never happen."));
end

rule "Detect alarm Stupid alarm rule 2_3"
when
	$s: String(this == "This should never happen.")
then
    System.out.println($s);
	System.out.println("Detected: Inaccessible alarm.");
	eventBus.onAlarm(new AlarmOccurred("Inaccessible alarm."));
end

rule "Detect alarm Stupid alarm rule 1_2"
when
	String(this == "This should never happen.")
then

	System.out.println("Detected: I told you this should never happen.");
	eventBus.onAlarm(new AlarmOccurred("I told you this should never happen."));
end

rule "Detect alarm Stupid alarm rule 2_1"
when
	$s: String(this == "This should never happen.")
then
    System.out.println($s);
	System.out.println("Detected: Inaccessible alarm.");
	eventBus.onAlarm(new AlarmOccurred("Inaccessible alarm."));
end

rule "Detect alarm Stupid alarm rule 1_0"
when
	String(this == "This should never happen.")
then

	System.out.println("Detected: I told you this should never happen.");
	eventBus.onAlarm(new AlarmOccurred("I told you this should never happen."));
end


