package bseprules;
global com.example.demo.bus.EventBus eventBus;
import com.example.demo.events.*;
import com.example.demo.logging.*;

rule "Detect alarm Stupid alarm rule 2_12"
when
	$s: String(this == "This should never happen.")
then
    System.out.println($s);
	System.out.println("Detected: Inaccessible alarm.");
	eventBus.onAlarm(new AlarmOccurred("Inaccessible alarm."));
end

rule "Detect alarm Stupid alarm rule 1_11"
when
	String(this == "This should never happen.")
then

	System.out.println("Detected: I told you this should never happen.");
	eventBus.onAlarm(new AlarmOccurred("I told you this should never happen."));
end

rule "Detect alarm Stupid alarm rule 2_10"
when
	$s: String(this == "This should never happen.")
then
    System.out.println($s);
	System.out.println("Detected: Inaccessible alarm.");
	eventBus.onAlarm(new AlarmOccurred("Inaccessible alarm."));
end

rule "Detect alarm Stupid alarm rule 1_9"
when
	String(this == "This should never happen.")
then

	System.out.println("Detected: I told you this should never happen.");
	eventBus.onAlarm(new AlarmOccurred("I told you this should never happen."));
end

rule "Detect alarm Stupid alarm rule 2_8"
when
	$s: String(this == "This should never happen.")
then
    System.out.println($s);
	System.out.println("Detected: Inaccessible alarm.");
	eventBus.onAlarm(new AlarmOccurred("Inaccessible alarm."));
end

rule "Detect alarm Stupid alarm rule 1_7"
when
	String(this == "This should never happen.")
then

	System.out.println("Detected: I told you this should never happen.");
	eventBus.onAlarm(new AlarmOccurred("I told you this should never happen."));
end

rule "Detect alarm Stupid alarm rule 2_6"
when
	$s: String(this == "This should never happen.")
then
    System.out.println($s);
	System.out.println("Detected: Inaccessible alarm.");
	eventBus.onAlarm(new AlarmOccurred("Inaccessible alarm."));
end

rule "Detect alarm Stupid alarm rule 1_5"
when
	String(this == "This should never happen.")
then

	System.out.println("Detected: I told you this should never happen.");
	eventBus.onAlarm(new AlarmOccurred("I told you this should never happen."));
end

rule "Detect alarm Stupid alarm rule 2_4"
when
	$s: String(this == "This should never happen.")
then
    System.out.println($s);
	System.out.println("Detected: Inaccessible alarm.");
	eventBus.onAlarm(new AlarmOccurred("Inaccessible alarm."));
end

rule "Detect alarm Stupid alarm rule 1_3"
when
	String(this == "This should never happen.")
then

	System.out.println("Detected: I told you this should never happen.");
	eventBus.onAlarm(new AlarmOccurred("I told you this should never happen."));
end

rule "Detect alarm novo pravilo_2"
when
	String(this == "pera")
String(this == "mika")
then

	System.out.println("Detected: pera i mika okinuli alarm");
	eventBus.onAlarm(new AlarmOccurred("pera i mika okinuli alarm"));
end

rule "Detect alarm Test pravilo_1"
when
	String(this == "test pravilo")
then

	System.out.println("Detected: Okinuto test pravilo");
	eventBus.onAlarm(new AlarmOccurred("Okinuto test pravilo"));
end

rule "Detect alarm Stupid alarm rule 1_0"
when
	String(this == "This should never happen.")
then

	System.out.println("Detected: I told you this should never happen.");
	eventBus.onAlarm(new AlarmOccurred("I told you this should never happen."));
end


