package bseprules;
global com.example.demo.bus.EventBus eventBus;
import com.example.demo.events.*;
import com.example.demo.logging.*;

rule "Detect alarm Stupid alarm rule 2_25"
when
	$s: String(this == "This should never happen.")
then
    System.out.println($s);
	System.out.println("Detected: Inaccessible alarm.");
	eventBus.onAlarm(new AlarmOccurred("Inaccessible alarm."));
end

rule "Detect alarm Stupid alarm rule 1_24"
when
	String(this == "This should never happen.")
then

	System.out.println("Detected: I told you this should never happen.");
	eventBus.onAlarm(new AlarmOccurred("I told you this should never happen."));
end

rule "Detect alarm Stupid alarm rule 2_23"
when
	$s: String(this == "This should never happen.")
then
    System.out.println($s);
	System.out.println("Detected: Inaccessible alarm.");
	eventBus.onAlarm(new AlarmOccurred("Inaccessible alarm."));
end

rule "Detect alarm Stupid alarm rule 1_22"
when
	String(this == "This should never happen.")
then

	System.out.println("Detected: I told you this should never happen.");
	eventBus.onAlarm(new AlarmOccurred("I told you this should never happen."));
end

rule "Detect alarm Stupid alarm rule 2_21"
when
	$s: String(this == "This should never happen.")
then
    System.out.println($s);
	System.out.println("Detected: Inaccessible alarm.");
	eventBus.onAlarm(new AlarmOccurred("Inaccessible alarm."));
end

rule "Detect alarm Stupid alarm rule 1_20"
when
	String(this == "This should never happen.")
then

	System.out.println("Detected: I told you this should never happen.");
	eventBus.onAlarm(new AlarmOccurred("I told you this should never happen."));
end

rule "Detect alarm Stupid alarm rule 2_19"
when
	$s: String(this == "This should never happen.")
then
    System.out.println($s);
	System.out.println("Detected: Inaccessible alarm.");
	eventBus.onAlarm(new AlarmOccurred("Inaccessible alarm."));
end

rule "Detect alarm Stupid alarm rule 1_18"
when
	String(this == "This should never happen.")
then

	System.out.println("Detected: I told you this should never happen.");
	eventBus.onAlarm(new AlarmOccurred("I told you this should never happen."));
end

rule "Detect alarm Stupid alarm rule 2_17"
when
	$s: String(this == "This should never happen.")
then
    System.out.println($s);
	System.out.println("Detected: Inaccessible alarm.");
	eventBus.onAlarm(new AlarmOccurred("Inaccessible alarm."));
end

rule "Detect alarm Stupid alarm rule 1_16"
when
	String(this == "This should never happen.")
then

	System.out.println("Detected: I told you this should never happen.");
	eventBus.onAlarm(new AlarmOccurred("I told you this should never happen."));
end

rule "Detect alarm Stupid alarm rule 2_15"
when
	$s: String(this == "This should never happen.")
then
    System.out.println($s);
	System.out.println("Detected: Inaccessible alarm.");
	eventBus.onAlarm(new AlarmOccurred("Inaccessible alarm."));
end

rule "Detect alarm Stupid alarm rule 1_14"
when
	String(this == "This should never happen.")
then

	System.out.println("Detected: I told you this should never happen.");
	eventBus.onAlarm(new AlarmOccurred("I told you this should never happen."));
end

rule "Detect alarm Stupid alarm rule 2_13"
when
	$s: String(this == "This should never happen.")
then
    System.out.println($s);
	System.out.println("Detected: Inaccessible alarm.");
	eventBus.onAlarm(new AlarmOccurred("Inaccessible alarm."));
end

rule "Detect alarm Stupid alarm rule 1_12"
when
	String(this == "This should never happen.")
then

	System.out.println("Detected: I told you this should never happen.");
	eventBus.onAlarm(new AlarmOccurred("I told you this should never happen."));
end

rule "Detect alarm Stupid alarm rule 2_11"
when
	$s: String(this == "This should never happen.")
then
    System.out.println($s);
	System.out.println("Detected: Inaccessible alarm.");
	eventBus.onAlarm(new AlarmOccurred("Inaccessible alarm."));
end

rule "Detect alarm Stupid alarm rule 1_10"
when
	String(this == "This should never happen.")
then

	System.out.println("Detected: I told you this should never happen.");
	eventBus.onAlarm(new AlarmOccurred("I told you this should never happen."));
end

rule "Detect alarm Stupid alarm rule 2_9"
when
	$s: String(this == "This should never happen.")
then
    System.out.println($s);
	System.out.println("Detected: Inaccessible alarm.");
	eventBus.onAlarm(new AlarmOccurred("Inaccessible alarm."));
end

rule "Detect alarm Stupid alarm rule 1_8"
when
	String(this == "This should never happen.")
then

	System.out.println("Detected: I told you this should never happen.");
	eventBus.onAlarm(new AlarmOccurred("I told you this should never happen."));
end

rule "Detect alarm Stupid alarm rule 2_7"
when
	$s: String(this == "This should never happen.")
then
    System.out.println($s);
	System.out.println("Detected: Inaccessible alarm.");
	eventBus.onAlarm(new AlarmOccurred("Inaccessible alarm."));
end

rule "Detect alarm Stupid alarm rule 1_6"
when
	String(this == "This should never happen.")
then

	System.out.println("Detected: I told you this should never happen.");
	eventBus.onAlarm(new AlarmOccurred("I told you this should never happen."));
end

rule "Detect alarm Stupid alarm rule 2_5"
when
	$s: String(this == "This should never happen.")
then
    System.out.println($s);
	System.out.println("Detected: Inaccessible alarm.");
	eventBus.onAlarm(new AlarmOccurred("Inaccessible alarm."));
end

rule "Detect alarm Stupid alarm rule 1_4"
when
	String(this == "This should never happen.")
then

	System.out.println("Detected: I told you this should never happen.");
	eventBus.onAlarm(new AlarmOccurred("I told you this should never happen."));
end

rule "Detect alarm Stupid alarm rule 2_3"
when
	$s: String(this == "This should never happen.")
then
    System.out.println($s);
	System.out.println("Detected: Inaccessible alarm.");
	eventBus.onAlarm(new AlarmOccurred("Inaccessible alarm."));
end

rule "Detect alarm Stupid alarm rule 1_2"
when
	String(this == "This should never happen.")
then

	System.out.println("Detected: I told you this should never happen.");
	eventBus.onAlarm(new AlarmOccurred("I told you this should never happen."));
end

rule "Detect alarm Stupid alarm rule 2_1"
when
	$s: String(this == "This should never happen.")
then
    System.out.println($s);
	System.out.println("Detected: Inaccessible alarm.");
	eventBus.onAlarm(new AlarmOccurred("Inaccessible alarm."));
end

rule "Detect alarm Stupid alarm rule 1_0"
when
	String(this == "This should never happen.")
then

	System.out.println("Detected: I told you this should never happen.");
	eventBus.onAlarm(new AlarmOccurred("I told you this should never happen."));
end


