package bseprules;
global kiber.bezbednjaci.bus.EventBus eventBus;
import kiber.bezbednjaci.events.*;
import kiber.bezbednjaci.logging.*;
import kiber.bezbednjaci.dto.message.*;
import kiber.bezbednjaci.model.*;
rule "Log alarm detected"
when
	e: DeviceAlarmTriggered()
then
	System.out.println("Device alarm triggered.");
	eventBus.onAlarm(e);
end

rule "Detect alarm Heart rate monitor measured Heart rate that is too high_7"
when
	    e1: DeviceMessageReceived(deviceId == 7, realEstateId == 1, value >= 170, value < 300)
    Number(intValue >= 3) from accumulate(
        e2: DeviceMessageReceived(
        deviceId == 7, realEstateId == 1,value >= 170, value < 300,
            this != e1,
            this meets[5m] e1
        ),
        count(e2)
    )
    not(
        DeviceAlarmTriggered(realEstateId == e1.getRealEstateId(), deviceId == e1.getDeviceId())
    )
then
    insert(new DeviceAlarmTriggered(e1.getRealEstateId(), e1.getDeviceId(), "Detected: Heart rate monitor measured Heart rate that is too high"));
	System.out.println("Detected: Heart rate monitor measured Heart rate that is too high");
end

rule "Detect alarm Barometer measured Air pressure that is too high_6"
when
	    e1: DeviceMessageReceived(deviceId == 6, realEstateId == 1, value >= 1030, value < 10000)
    Number(intValue >= 3) from accumulate(
        e2: DeviceMessageReceived(
        deviceId == 6, realEstateId == 1,value >= 1030, value < 10000,
            this != e1,
            this meets[5m] e1
        ),
        count(e2)
    )
    not(
        DeviceAlarmTriggered(realEstateId == e1.getRealEstateId(), deviceId == e1.getDeviceId())
    )
then
    insert(new DeviceAlarmTriggered(e1.getRealEstateId(), e1.getDeviceId(), "Detected: Barometer measured Air pressure that is too high"));
	System.out.println("Detected: Barometer measured Air pressure that is too high");
end

rule "Detect alarm Thermometer measured Temperature that is too high_5"
when
	    e1: DeviceMessageReceived(deviceId == 5, realEstateId == 3, value >= 22, value < 200)
    Number(intValue >= 3) from accumulate(
        e2: DeviceMessageReceived(
        deviceId == 5, realEstateId == 3,value >= 22, value < 200,
            this != e1,
            this meets[5m] e1
        ),
        count(e2)
    )
    not(
        DeviceAlarmTriggered(realEstateId == e1.getRealEstateId(), deviceId == e1.getDeviceId())
    )
then
    insert(new DeviceAlarmTriggered(e1.getRealEstateId(), e1.getDeviceId(), "Detected: Thermometer measured Temperature that is too high"));
	System.out.println("Detected: Thermometer measured Temperature that is too high");
end

rule "Detect alarm Air Humidity Meter Measured Humidity that is too high_4"
when
	    e1: DeviceMessageReceived(deviceId == 4, realEstateId == 3, value >= 55, value < 200)
    Number(intValue >= 3) from accumulate(
        e2: DeviceMessageReceived(
        deviceId == 4, realEstateId == 3,value >= 55, value < 200,
            this != e1,
            this meets[5m] e1
        ),
        count(e2)
    )
    not(
        DeviceAlarmTriggered(realEstateId == e1.getRealEstateId(), deviceId == e1.getDeviceId())
    )
then
    insert(new DeviceAlarmTriggered(e1.getRealEstateId(), e1.getDeviceId(), "Detected: Air Humidity Meter Measured Humidity that is too high"));
	System.out.println("Detected: Air Humidity Meter Measured Humidity that is too high");
end

rule "Detect alarm Door handle pulled while doors were locked_3"
when
	    e1: DeviceMessageReceived(deviceId == 3, realEstateId == 2, value >= 2, value < 3)
    Number(intValue >= 3) from accumulate(
        e2: DeviceMessageReceived(
        deviceId == 3, realEstateId == 2,value >= 2, value < 3,
            this != e1,
            this meets[5m] e1
        ),
        count(e2)
    )
    not(
        DeviceAlarmTriggered(realEstateId == e1.getRealEstateId(), deviceId == e1.getDeviceId())
    )
then
    insert(new DeviceAlarmTriggered(e1.getRealEstateId(), e1.getDeviceId(), "Detected: Door handle pulled while doors were locked"));
	System.out.println("Detected: Door handle pulled while doors were locked");
end

rule "Detect alarm Unsuccessful unlock attempt_2"
when
	    e1: DeviceMessageReceived(deviceId == 3, realEstateId == 2, value >= 3, value < 4)
    Number(intValue >= 3) from accumulate(
        e2: DeviceMessageReceived(
        deviceId == 3, realEstateId == 2,value >= 3, value < 4,
            this != e1,
            this meets[5m] e1
        ),
        count(e2)
    )
    not(
        DeviceAlarmTriggered(realEstateId == e1.getRealEstateId(), deviceId == e1.getDeviceId())
    )
then
    insert(new DeviceAlarmTriggered(e1.getRealEstateId(), e1.getDeviceId(), "Detected: Unsuccessfull unlock attempt"));
	System.out.println("Detected: Unsuccessful unlock attempt");
end

rule "Detect alarm Light switch turned on_1"
when
	    e1: DeviceMessageReceived(deviceId == 2, realEstateId == 1, value >= 1)
    Number(intValue >= 3) from accumulate(
        e2: DeviceMessageReceived(
        deviceId == 2, realEstateId == 1,value >= 1,
            this != e1,
            this meets[5m] e1
        ),
        count(e2)
    )
    not(
        DeviceAlarmTriggered(realEstateId == e1.getRealEstateId(), deviceId == e1.getDeviceId())
    )
then
    insert(new DeviceAlarmTriggered(e1.getRealEstateId(), e1.getDeviceId(), "Detected: Light switch turned on"));
	System.out.println("Detected: Light switch turned on");
end

rule "Detect alarm Camera_0"
when
	    e1: DeviceMessageReceived(deviceId == 1, realEstateId == 1, value >= 1)
    Number(intValue >= 3) from accumulate(
        e2: DeviceMessageReceived(
        deviceId == 1, realEstateId == 1,value >= 1,
            this != e1,
            this meets[5m] e1
        ),
        count(e2)
    )
    not(
        DeviceAlarmTriggered(realEstateId == e1.getRealEstateId(), deviceId == e1.getDeviceId())
    )
then
    insert(new DeviceAlarmTriggered(e1.getRealEstateId(), e1.getDeviceId(), "Camera detection happened"));
	System.out.println("Detected: Camera detection happened");
end


